### ISSUE TITLE
Colimits in HoTT

### ISSUE THREAD

**Issue by andrejbauer** [nmvdw/Three-HITs#1]
There is an outstanding PR request for a colimits library in HoTT, see https://github.com/HoTT/HoTT/pull/850. We probably shouldn't duplicate the effort needlessly.

**Comment by andrejbauer** [comment]
So do these help us in any way?

**Comment by nmvdw** [comment]
It would shorten the code since the definition of the colimit can then be imported. I don't know yet how to import it.
